export const VIEW_DISPONIBILITY_SUCCESS = "VIEW_DISPONIBILITY_SUCCESS";
export const VIEW_DISPONIBILITY_FAIL = "VIEW_DISPONIBILITY_FAIL";
export const VIEW_DISPONIBILITY_LOAD = "VIEW_DISPONIBILITY_LOAD";
export const UPDATE_DISPONIBILITY_SUCCESS = "UPDATE_DISPONIBILITY_SUCCESS";
export const UPDATE_DISPONIBILITY_FAIL = "UPDATE_DISPONIBILITY_FAIL";
export const UPDATE_DISPONIBILITY_DAY_SUCCESS =
  "UPDATE_DISPONIBILITY_DAY_SUCCESS";
export const UPDATE_DISPONIBILITY_DAY_FAIL = "UPDATE_DISPONIBILITY_DAY_FAIL";
