export const LIST_MEDECINS_LOAD = "LIST_MEDECINS_LOAD";
export const LIST_MEDECINS_SUCCESS = "LIST_MEDECINS_SUCCESS";
export const LIST_MEDECINS_FAIL = "LIST_MEDECINS_FAIL";

export const CURRENT_DOCTOR = "CURRENT_DOCTOR";

export const GET_ONEDOCTOR_SUCCESS = "GET_ONEDOCTOR_SUCCESS";
export const GET_ONEDOCTOR_FAIL = "GET_ONEDOCTOR_FAIL";

export const LOGIN_MEDECIN_LOAD = "LOGIN_MEDECIN_LOAD";
export const LOGIN_MEDECIN_SUCCESS = "LOGIN_MEDECIN_SUCCESS";
export const LOGIN_MEDECIN_FAIL = "LOGIN_MEDECIN_FAIL";

export const UPDATE_MEDECIN_SUCCESS = "UPDATE_MEDECIN_SUCCESS";
export const UPDATE_MEDECIN_FAIL = "UPDATE_MEDECIN_FAIL";

export const LOGOUT_MEDECIN = "LOGOUT_MEDECIN";
