export const CREATE_RDV_LOAD = "CREATE_RDV_LOAD";
export const CREATE_RDV_SUCCESS = "CREATE_RDV_SUCCESS";
export const CREATE_RDV_FAIL = "CREATE_RDV_FAIL";

export const GET_RDV_USER_LOAD = "GET_RDV_USER_LOAD";
export const GET_RDV_USER_SUCCESS = "GET_RDV_USER_SUCCESS";
export const GET_RDV_USER_FAIL = "GET_RDV_USER_FAIL";

export const GET_RDV_MEDECIN_LOAD = "GET_RDV_MEDECIN_LOAD";
export const GET_RDV_MEDECIN_SUCCESS = "GET_RDV_MEDECIN_SUCCESS";
export const GET_RDV_MEDECIN_FAIL = "GET_RDV_MEDECIN_FAIL";

export const RDV_UPDATE_SUCCESS = "RDV_UPDATE_SUCCESS";
export const RDV_UPDATE_FAIL = "RDV_UPDATE_FAIL";

export const RDV_DELETE_SUCCESS = "RDV_DELETE_SUCCESS";
export const RDV_DELETE_FAIL = "RDV_DELETE_FAIL";
